# -----------------------------------------------------
# Project Identification
# -----------------------------------------------------
sonar.projectKey=lemoncompanies_lemon_studio_template
sonar.organization=lemoncompanies

# -----------------------------------------------------
# Source Configuration
# -----------------------------------------------------
sonar.sources=.
sonar.sourceEncoding=UTF-8

# -----------------------------------------------------
# Exclusion Patterns
# -----------------------------------------------------
# Files and directories to exclude from analysis
sonar.exclusions=**/node_modules/**,\
                 **/.idea/**,\
                 **/.husky/**,\
                 **/.DS_Store,\
                 **/yarn.lock,\
                 **/packages/**e2e**/**,\
                 **/bundles/**,\
                 **/gql/**

sonar.coverage.exclusions=**/node_modules/**,\
                     **/.idea/**,\
                     **/.husky/**,\
                     **/.DS_Store,\
                     **/yarn.lock,\
                     **/packages/**e2e**/**,\
                     **/bundles/**,\
                     **/gql/**

# Files and directories to exclude from duplication detection
sonar.cpd.exclusions=**/node_modules/**,\
                     **/.idea/**,\
                     **/.husky/**,\
                     **/.DS_Store,\
                     **/yarn.lock,\
                     **/packages/**e2e**/**,\
                     **/bundles/**,\
                     **/gql/**

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
