rules:
    'func-names': off
    'no-restricted-imports':
        [
            error,
            {
                paths:
                    [
                        {
                            name: '@playwright/test',
                            importNames: ['expect'],
                            'message': "Please import expect from './util/expect'",
                        },
                    ],
            },
        ]
