/**
 * RRule always return occurrence dates in the local timezone, but with the UTC offset applied.
 * For example, if a recurring event should be created at 10:00 in Europe/Brussels and the machine
 * running the code is in Asia/Tokyo, RRule will return occurrence dates at 18:00 (10:00 + 8 hours offset).
 * But the date will be "2025-01-15T18:00:00.000Z", which is incorrect because of the Z at thn end.
 *
 * We stringify the date, cut off the Z, and create a new Date object to have it interpreted
 * in the local timezone of the machine running the code.
 *
 * @param date a date generated by RRule using for example .between(...)
 */
export function cleanRRuleOccurrenceDate(date: Date): Date {
    const dateString = date.toISOString();
    const dateStringWithoutZ = dateString.replace(/Z$/, '');
    return new Date(dateStringWithoutZ);
}
