services:
    mongodb:
        hostname: package-name_database
        container_name: package-name_database
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

    mssql:
        hostname: package-name_mssql
        container_name: package-name_mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - '1433:1433'
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: yourStrong!Password
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'yourStrong!Password' -Q 'SELECT 1' -C || exit 1",
                ]
            interval: 10s
            retries: 10
            start_period: 10s
            timeout: 3s
    mssql.init:
        hostname: package-name_mssql.init
        container_name: package-name_mssql.init
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes:
            - ./mssql:/docker-entrypoint-initdb.d
        depends_on:
            mssql:
                condition: service_healthy
        command: >
            bash -c '
            /opt/mssql-tools18/bin/sqlcmd -C -S mssql -U sa -P 'yourStrong!Password' -d master -i /docker-entrypoint-initdb.d/init.sql;
            echo "All done!";
            '

    mock-server:
        hostname: package-name_external_http_services
        container_name: package-name_external_http_services
        image: mockserver/mockserver:latest
        ports:
            - '1080:1080'
        environment:
            MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
        volumes:
            - type: bind
              source: ./mockserver
              target: /config
    fake-idp:
        hostname: package-name_idp
        container_name: package-name_fake_idp
        image: spectare/oidc-token-test-service:latest
        ports:
            - '2377:2377'
        environment:
            BIND: 0.0.0.0
            PORT: 2377
            EXPOSED_HOST: 'http://package-name_idp:2377'
    localstack:
        container_name: 'package-name_localstack'
        image: localstack/localstack:latest
        ports:
            - '4566:4566' # LocalStack Gateway
        environment:
            - SERVICES=s3:4566
        volumes:
            - ./localstack/init:/etc/localstack/init/ready.d

volumes:
    mongo-data:
