name: Update disclaimer

on:
    push:
        branches:
            - main
        paths:
            - 'yarn.lock'

permissions:
    contents: write

jobs:
    update-disclaimer:
        name: Update disclaimer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set git config
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Install dependencies
              run: yarn --immutable

            - name: Generate disclaimer
              run: yarn generate-disclaimer

            - name: Push disclaimer
              run: |
                  git add disclaimer.txt
                  git commit -m "[ci] chore: update disclaimer"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
